export { default as Home } from './Home';
export { default as BirthInput } from './BirthInput';
export { default as Chat } from './Chat';
export { default as Report } from './Report';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Profile } from './Profile';
export { default as Community } from './Community';
export { default as VisualNovel } from './VisualNovel';